---
title: "Interactive Hydrology Lessons"
author: "Matthew Ross"
date: "8/11/2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---


# Hydrology Online

This project is funded by the NSF RAPID Hydrologic Sciences program (Award 2028778). It's meant to make teaching courses online easier and better (sensu [Sal Khan of Khan Academy)](https://www.nytimes.com/2020/08/13/opinion/coronavirus-school-digital.html).
The team includes:

- Anna Bergstrom
- Tim Covino
- Karin Emanuelson
- Bryce Pulver
- Matt Ross
- [The much larger RAPID team](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2028737&HistoricalAwards=false)
- CUAHSI

This landing page is under construction. But we wanted to share our first
complete sets of lectures/homework/applications. Eventually we hope a bunch
of people will contribute to this page and [hydrolearn](https://www.hydrolearn.org/),
which helped inspire our approach. 

## Fully developed modules

These modules contain video lectures, assignments, grading rubric and overall
module goals. 


### Hydrograph Separation (Anna Bergstrom)

  - [Baseflow and Stormflow lecture and text](hydrology/1_baseflow_stormflow/0_hydrograph_separation_lecture.html)

  - Rubric [here](hydrology/1_baseflow_stormflow/Hydrolearn_OUtline_Baseflow.pdf)
  
  - Analysis assessment [here](https://cuahsi.shinyapps.io/1_baseflow_vs_stormflow/)
  
  - Interactive web app on mountaintop mining impacts to streamflow [here](https://cuahsi.shinyapps.io/mtm_baseflow/)
  
### Velocity Area (Covino lab)
  
  - [Velocity Area lecture and text](hydrology/2_velocity_area_module/2_velocity_area_module.html)
  
  - Rubric [here](hydrology/2_velocity_area_module/2_velocity_area_module_files/velocity_area_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/pp7spwyk9maa4ul/Velo_Area_Assessment.xlsx?dl=0)
  
### Dilution Gauging (Covino lab)

  - [Dilution Gauging lecture and text](hydrology/3_dilution_gauging/3_dilution_gauging.html)
  
  - Rubric [here](hydrology/3_dilution_gauging/3_dilution_gauging_files/dilution_gauging_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/hkpucfp1g7lhlj3/DG_Assessment.xlsx?dl=0)
  
###  Stream Health (Covino lab)

  - [Stream Health lecture and text](hydrology/4_stream_health/4_stream_health.html)
  
  - Analysis assessment [here](https://www.dropbox.com/s/9cmi8a1w448q41e/Stream_Health_Assesment.pdf?dl=0)

### Meteorological Measurements (Covino lab)

  - [Meteorological Measurements lecture and text](hydrology/5_met_lab/5_met_lab.html)

### Fluvial Geomorphology (Covino lab)

  - [Fluvial Geomorphology lecture and text](hydrology/6_geomorph/6_geomorph.html)
  
  - Rubric [here](hydrology/6_geomorph/6_geomorph_files/geomorph_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/x5ullpuu2lu33yd/Mannings_Assessment.xlsx?dl=0)


## Stand alone shiny apps

These applications have no teaching material associated with them, but could
be easily included into class exercises or homeworks. 

- [Colorado Streamflow and Watershed Attributes (Stephanie Kampf)](https://cuahsi.shinyapps.io/CO_streamflow/)

- [Hubbard Brook Experimental Forest Discharge by JP Gannon](https://cuahsi.shinyapps.io/HBEF_Discharge/)

- [Joyful Q by Lauren Steely](https://lsteely.shinyapps.io/streamflow_joyplots/)

<br> 
<br> 

# Biogeochemistry online

We have spent considerably more time developing the hydrology portion of this work,
but plan on developing more biogeochemistry modules soon. In the meantime we have
several shinyapps that could be used for interactive teaching. 

## Stand Alone shiny applications

- [Water quality change in blue river watershed, CO](https://cuahsi.shinyapps.io/blue_watershed/)

- [Weathering impacts from mountaintop mining](https://cuahsi.shinyapps.io/mtm_weathering/)

- [National water quality inventories and data](http://waterqualityexplorer.rc.duke.edu:3838/explorer/)


# Acknowledgements 

This work is a collaborative effort across many groups and is funded by an 
[NSF RAPID #2028737](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2028737&HistoricalAwards=false). We hope to keep expanding and are eager for community contributions through
GitHub or directly contacting team members. 

The main contributors to the page so far are: 

- [Tim Covino and his lab](https://covinocsuwatershed.weebly.com/people.html), specifically Karin Emanuelson and Alison Rhea

- [Anna Bergstrom](https://anna-bergstrom.weebly.com/), soon to be Asst. Prof at Boise State

- Bryce Pulver, graduate student in Stephanie Kampf's lab

- [Matt Ross](https://matthewrvross.com/)
